"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var React = __importStar(require("react"));
exports.React = React;
var mobx_1 = require("mobx");
exports.action = mobx_1.action;
exports.observable = mobx_1.observable;
var client_1 = __importDefault(require("./core/client"));
exports.Client = client_1.default;
var Entity_1 = __importDefault(require("./core/storage/Entity"));
exports.Entity = Entity_1.default;
var Link_1 = __importDefault(require("./core/routes/Link"));
exports.Link = Link_1.default;
var logger_1 = __importDefault(require("./core/client/logger"));
exports.logger = logger_1.default;
var mobx_react_1 = require("mobx-react");
exports.observer = mobx_react_1.observer;
var Repository_1 = __importDefault(require("./core/storage/Repository"));
exports.Repository = Repository_1.default;
var Route_1 = __importDefault(require("./core/routes/Route"));
exports.Route = Route_1.default;
var Redirect_1 = __importDefault(require("./core/routes/Redirect"));
exports.Redirect = Redirect_1.default;
var Router_1 = __importDefault(require("./core/routes/Router"));
exports.Router = Router_1.default;
var Database_1 = __importDefault(require("./core/storage/Database"));
exports.Database = Database_1.default;
var Store_1 = __importDefault(require("./core/stores/Store"));
exports.Store = Store_1.default;
var WebComponent_1 = __importDefault(require("./core/components/WebComponent"));
exports.WebComponent = WebComponent_1.default;
var WebPage_1 = __importDefault(require("./core/components/WebPage"));
exports.WebPage = WebPage_1.default;
var Languages_1 = __importDefault(require("./core/i18n/Languages"));
exports.Languages = Languages_1.default;
var stringsByCount_1 = __importDefault(require("./core/i18n/stringsByCount"));
exports.stringsByCount = stringsByCount_1.default;
var stringsByLanguage_1 = __importDefault(require("./core/i18n/stringsByLanguage"));
exports.stringsByLanguage = stringsByLanguage_1.default;
var i18n_1 = __importDefault(require("./core/i18n"));
exports.i18n = i18n_1.default;
